### ISSUE TITLE
x

### ISSUE THREAD

**Issue by oleanderghum** [oleanderghum/x#1]
I made some adjustment

**Comment by shayymaa** [comment]
I’m trying to register a new account with a new email address

**Comment by shayymaaxx** [comment]
can wetalk here?

**Comment by oleanderghum** [comment]
Ah finally

**Comment by shayymaaxx** [comment]
what's going on...😂😂 i can still receive email from here,i mean my former address😂😂😂just like we have three here

**Comment by shayymaaxx** [comment]
that's. odd

**Comment by shayymaaxx** [comment]
any way to fix it?😂

**Comment by shayymaaxx** [comment]
hey where are you

**Comment by oleanderghum** [comment]
I logged your former account and sent a help message to the backstage admin half hour ago

**Comment by shayymaaxx** [comment]
oh that's all.i managed it

**Comment by shayymaaxx** [comment]
lets forget about that, lets talk

**Comment by oleanderghum** [comment]
COOL, LET US

**Comment by oleanderghum** [comment]
Do you want to live abroad

**Comment by shayymaaxx** [comment]
ohhh.. not easy to talk to you for a while

**Comment by shayymaaxx** [comment]
you mean never come back?

**Comment by oleanderghum** [comment]
YES

**Comment by shayymaaxx** [comment]
that's difficult,and..impractical.

**Comment by oleanderghum** [comment]
what about come back whenever you want

**Comment by shayymaaxx** [comment]
what are you thinking about?

**Comment by oleanderghum** [comment]
Do want to live abroad? Ever think about it?

**Comment by shayymaaxx** [comment]
sure i did think about it,but i don't know.

**Comment by oleanderghum** [comment]
Europe, North America, Gulf countries, you will choose?

**Comment by shayymaaxx** [comment]
of course for me the good choice are gulf countries

**Comment by oleanderghum** [comment]
like Dubai?

**Comment by oleanderghum** [comment]
Leave, live abroad

**Comment by shayymaaxx** [comment]
how to leave

**Comment by oleanderghum** [comment]
The first step is make up mind

**Comment by oleanderghum** [comment]
Then latter part is much easier

**Comment by shayymaaxx** [comment]
why im holding a different idea?I don't think that blueprint helps, it can only drop us down,deep deep down. making up our mind is easy, all i want is being with you, but to make it come true,that pays heavily,i just realized it these days. how you will deal with your problems? with your wife, your family, your marriage,and your parents?i don't want a besotted result, and, i can't push you,either.what can we do?

**Comment by shayymaaxx** [comment]
even I don't know whether i have the courage to leave with my mum left,or. .i don't know..so many things.

**Comment by shayymaaxx** [comment]
im just soooooo avaricious ,but incompatible

**Comment by shayymaaxx** [comment]
let's not talk about this here, im sure it's not a good place to discuss our problem, this kind of problem need to be put on the table when we finally sit together

**Comment by oleanderghum** [comment]
I'm tackling my issues

**Comment by oleanderghum** [comment]
And it's not a blueprint,it's the next step

**Comment by shayymaaxx** [comment]
take your time, don't be so hard. you don't know I'm worried about you everyday every moment

**Comment by oleanderghum** [comment]
Just don't want you to wait too long

**Comment by shayymaaxx** [comment]
believ me, i wont push you anymore,it's not my intention to see you live in an abyss of suffering, and that's because of me,which really kills me

**Comment by shayymaaxx** [comment]
im in a contradiction

**Comment by oleanderghum** [comment]
It kills both of us. We live we die, and we live again

**Comment by shayymaaxx** [comment]
what should I do

**Comment by oleanderghum** [comment]
Are you afraid?

**Comment by shayymaaxx** [comment]
afraid of what

**Comment by oleanderghum** [comment]
Incoming storm

**Comment by shayymaaxx** [comment]
im not planing to hide,i chose nowhere for me to hide

**Comment by oleanderghum** [comment]
You don't have to take it, you should hide, when the sun and blue sky and rainbow comes out

**Comment by shayymaaxx** [comment]
you want a girl does nothing for the future of both of you?

**Comment by shayymaaxx** [comment]
im still waiting just to give you enough time, doesn't mean I'll do nothing.

**Comment by shayymaaxx** [comment]
after my long waiting,if you don't make it,then we'll  face it together,or we quit. there are just these two choices for us, nothing more

**Comment by oleanderghum** [comment]
So what you can do? 🙂

**Comment by shayymaaxx** [comment]
i don't know, it depends.

**Comment by shayymaaxx** [comment]
depends on what i think you need me to do

**Comment by shayymaaxx** [comment]
you are right, i can do nothing for you

**Comment by shayymaaxx** [comment]
i finally realized that,so how could I ask more?

**Comment by oleanderghum** [comment]
That's rational

**Comment by shayymaaxx** [comment]
let's just..don't talk about this here, it makes my precious chatting time with you a tough time, I don't allow this

**Comment by oleanderghum** [comment]
You are right, we should talk about exciting things like mix😆😆

**Comment by oleanderghum** [comment]
You are right, we should talk about exciting things like mix😆😆

**Comment by oleanderghum** [comment]
You are right, we should talk about exciting things like mix😆😆

**Comment by oleanderghum** [comment]
You are right, we should talk about exciting things like mix😆😆

**Comment by oleanderghum** [comment]
Feel like I'm a hooligan😎😒

**Comment by oleanderghum** [comment]
Or I really am?

**Comment by oleanderghum** [comment]
You got headache, I got insomniac, seems like we both got a loyal friend

**Comment by oleanderghum** [comment]
Yeah I'm a hooligan

**Comment by shayymaaxx** [comment]
you drunk yesterday?

**Comment by shayymaaxx** [comment]
sorry i was asleep

**Comment by oleanderghum** [comment]
Didn't drink, just insomniac

**Comment by shayymaaxx** [comment]
what time did you sleep

**Comment by oleanderghum** [comment]
3am maybe

**Comment by shayymaaxx** [comment]
want me to have long hair or short

**Comment by oleanderghum** [comment]
As you wish, short better

**Comment by shayymaaxx** [comment]
why short better

**Comment by oleanderghum** [comment]
Cute

**Comment by shayymaaxx** [comment]
im cute all the way

**Comment by shayymaaxx** [comment]
in any shape

**Comment by shayymaaxx** [comment]
im born with it

**Comment by shayymaaxx** [comment]
ain't I?

**Comment by shayymaaxx** [comment]
😌

**Comment by oleanderghum** [comment]
Cut it or leave it, that is a question

**Comment by shayymaaxx** [comment]
depends on my mind

**Comment by shayymaaxx** [comment]
why you ignored my words👿

**Comment by shayymaaxx** [comment]
don't you.see that im eager for your nod??you bad guy

**Comment by oleanderghum** [comment]
Cute cute you born this way

**Comment by shayymaaxx** [comment]
late😠

**Comment by oleanderghum** [comment]
Oh, wow, what come next

**Comment by shayymaaxx** [comment]
i don't know,

**Comment by shayymaaxx** [comment]
you guess

**Comment by shayymaaxx** [comment]
snubbing you?

**Comment by shayymaaxx** [comment]
ignoring you?

**Comment by oleanderghum** [comment]
Name it

**Comment by shayymaaxx** [comment]
what

**Comment by oleanderghum** [comment]
😎😎

**Comment by oleanderghum** [comment]
What do you do for fun

**Comment by shayymaaxx** [comment]
these days?

**Comment by oleanderghum** [comment]
Yes and today

**Comment by shayymaaxx** [comment]
today😂😂  I spent my day  at barber's accompanying my mum,watching her changing her haircut.

**Comment by shayymaaxx** [comment]
so..accompanying her as my fun today?😂😂

**Comment by shayymaaxx** [comment]
are you going to share yours?

**Comment by oleanderghum** [comment]
Talk to you here

**Comment by oleanderghum** [comment]
Is the only and all

**Comment by shayymaaxx** [comment]
you reminded me of my own way,usually, when i want some fun i just walk out alone,watching everything around me and follow my thoughts without any constrain, what's strange is that i can always find my peace and fun in this way

**Comment by shayymaaxx** [comment]
try mine?

**Comment by oleanderghum** [comment]
Will try

**Comment by shayymaaxx** [comment]
oh...normal person use her normal way,hhhhh 
i just find that i have no exact way to have fun, pity. dealing with normal things gives me fun maybe

**Comment by oleanderghum** [comment]
I used to have a very strange ability, sounds untrue.Years ago, maybe 2 or 3, I was capable control my dream

**Comment by shayymaaxx** [comment]
maybe you can give me some different experience

**Comment by oleanderghum** [comment]
I cherish this ability very much, and I rarely use it, only when I'm extremely upset or hopeless

**Comment by oleanderghum** [comment]
The more the situation is extreme, I get more possibility to dream what I plan before fall asleep

**Comment by shayymaaxx** [comment]
mutant?

**Comment by shayymaaxx** [comment]
soCOOL

**Comment by oleanderghum** [comment]
Place, people, mood is defined, but the season, weather, incident and the ending can't be prelimited

**Comment by oleanderghum** [comment]
😒

**Comment by oleanderghum** [comment]
And I need to prepare some liqueur, fine like rum of vodka

**Comment by oleanderghum** [comment]
rum or vodka

**Comment by oleanderghum** [comment]
So called _Cheap Thrill_

**Comment by shayymaaxx** [comment]
Come on come on turn the radio on

**Comment by oleanderghum** [comment]
HAHA l repeat that song all day long, can't put it down

**Comment by shayymaaxx** [comment]
haven't you heard this song before？

**Comment by oleanderghum** [comment]
HEARD IT BEFORE, BUT YESTERDAY WANTED TO REPEAT

**Comment by shayymaaxx** [comment]
why yesterday,got something excited?

**Comment by oleanderghum** [comment]
I think it's a sad song?

**Comment by shayymaaxx** [comment]
maybe content with own lot

**Comment by oleanderghum** [comment]
No, I mean, when I listening, I was thinking about me and you, a friday night, back to our apartment, then we enjoy the friday night

**Comment by oleanderghum** [comment]
Hang out or stay put, anywhere I'm fine with it

**Comment by shayymaaxx** [comment]
now you give me FANTASY

**Comment by oleanderghum** [comment]
Listen once, imagine twice

**Comment by shayymaaxx** [comment]
coincidence, I've imagined countless pictures with you,how you cook for me, how you look at me, how we read together but enjoy doing things apart meanwhile,how i hug you,how i smile at you,how you caressing my hair,how you kiss me

**Comment by oleanderghum** [comment]
What a coincidence

**Comment by oleanderghum** [comment]
You sleep? I took a nap but ...damn

**Comment by oleanderghum** [comment]
Sweet dream

**Comment by oleanderghum** [comment]
💤💤

**Comment by oleanderghum** [comment]
Uhhhhhhhh still can't sleep

**Comment by oleanderghum** [comment]
😑😑😑

**Comment by shayymaaxx** [comment]
hey you... usually I hold my phone waiting for your messages and fall asleep.
I know a way that you should manage your breathing, adjust your frequency of it gently slow your inhalations and exhalations, try to  focus on the rhythm of your breathing,find a comfort rhythm. i don't know...maybe it can help, I tried once, it helped. 
maybe just because....that you think too much, 
hey,don't push yourself okay?

**Comment by shayymaaxx** [comment]
I'm worried about you,intensely

**Comment by oleanderghum** [comment]
Yes I'll try. Maybe I'm a "hard man ", sleep hard live hard? 😄

**Comment by shayymaaxx** [comment]
and you met me...harder??😂😂

**Comment by oleanderghum** [comment]
Drink hard, play hard and......hard😆

**Comment by shayymaaxx** [comment]
and live harder?

**Comment by shayymaaxx** [comment]
you enjoyed it,huh?

**Comment by oleanderghum** [comment]
Some hards are torture, some feel good

**Comment by shayymaaxx** [comment]
like what tortures you

**Comment by oleanderghum** [comment]
Domestic affairs

**Comment by oleanderghum** [comment]
😕

**Comment by oleanderghum** [comment]
Hanging out?

**Comment by oleanderghum** [comment]
😕

**Comment by shayymaaxx** [comment]
just...don't know how to get you out of your troubles,and im the source....made me at a loss, don't know what to say

**Comment by shayymaaxx** [comment]
what did you do today

**Comment by oleanderghum** [comment]
Searching for some informations，

**Comment by oleanderghum** [comment]
I need to direct a drama, and need your help, to perform along with me

**Comment by oleanderghum** [comment]
I think the lines would be a little hard for you

**Comment by oleanderghum** [comment]
A little bit cruel, hard to start

**Comment by shayymaaxx** [comment]
im not good at.that

**Comment by oleanderghum** [comment]
Really hope you can help

**Comment by shayymaaxx** [comment]
how

**Comment by oleanderghum** [comment]
recite the lines

**Comment by oleanderghum** [comment]
which means conversation prepared before

**Comment by shayymaaxx** [comment]
can't follow you, what drama?why?why me?we show it to whom ?

**Comment by shayymaaxx** [comment]
to your wife? or whom

**Comment by oleanderghum** [comment]
yes, to her

**Comment by oleanderghum** [comment]
because it is time to pretend

**Comment by shayymaaxx** [comment]
pretend what

**Comment by oleanderghum** [comment]
I‘ve been think this for days, since the day I deleted your account, then I find this way out. I've been through a bloody battle in these days, it's heavy and complicated, I will tell you whole story after we win this war

**Comment by shayymaaxx** [comment]
can we win? what does our WIN mean? what kind of win?

**Comment by shayymaaxx** [comment]
i even don't know what happened till now,im always at a mess,what can i do?how can i do?

**Comment by oleanderghum** [comment]
It's a war, and this, is the first campaign we can't lose.

**Comment by shayymaaxx** [comment]
why you just tell me everything, don't you know that made me feel like a FOOL????!!!

**Comment by shayymaaxx** [comment]
like an idiot

**Comment by oleanderghum** [comment]
I tell you everything

**Comment by oleanderghum** [comment]
I've never tried to fool you or make you a fool, never.

**Comment by oleanderghum** [comment]
I didn't tell you because I don't want you to undertake this burden

**Comment by oleanderghum** [comment]
But now I guess I have no other choice but tell you.

**Comment by oleanderghum** [comment]
I told her. Then you can imagine what has been through in the week past

**Comment by oleanderghum** [comment]
Hope you not mad at me,for made such decision

**Comment by oleanderghum** [comment]
And don't worry

**Comment by shayymaaxx** [comment]
and?what did she say,what does she want?
why you decided to do that

**Comment by oleanderghum** [comment]
Then storm came, all pressure I'm under

**Comment by shayymaaxx** [comment]
means?

**Comment by oleanderghum** [comment]
What would a wife reaction when she knows, you know.

**Comment by oleanderghum** [comment]
Now the only one thing I want is you can stick together with me

**Comment by oleanderghum** [comment]
?

**Comment by shayymaaxx** [comment]
i think we urgently need to talk,but it's impossible to you, so i wanna some answers,not thus ambiguous trope

**Comment by shayymaaxx** [comment]
why you decided to tell her,what's your purpose

**Comment by shayymaaxx** [comment]
divorce?

**Comment by oleanderghum** [comment]
RIGHT

**Comment by shayymaaxx** [comment]
why you chose that day?

**Comment by oleanderghum** [comment]
It's not chosen, it's instinct, suddenly I felt I can't stay here one second more

**Comment by shayymaaxx** [comment]
so you delete my account to protect me from them? don't want them know who i am?or?

**Comment by oleanderghum** [comment]
They knew

**Comment by oleanderghum** [comment]
Name, age, where you from, graduate student, so far

**Comment by shayymaaxx** [comment]
i can't follow you,so your parents knew me,right?your wife ,knew me before you told her or because you told her, and them?

**Comment by oleanderghum** [comment]
My parent don't know yet, her parent does. After I told her.

**Comment by oleanderghum** [comment]
The worst thing and the reason I told you to play a show with me is that she wanted to give you a hard time.

**Comment by shayymaaxx** [comment]
So they told you to leave me? And you're afraid they're calling me?

**Comment by shayymaaxx** [comment]
what kind of hard time? what's her plan?😄

**Comment by shayymaaxx** [comment]
how did she knew who i am? by the way of your phone?

**Comment by oleanderghum** [comment]
No, they didn't told me that, they tried to let the school to expel you. I stopped them and told them I would no longer have any contact in any situation.

**Comment by oleanderghum** [comment]
Now how why what doesn't matter, only to let them give up this action matters

**Comment by shayymaaxx** [comment]
i guess they wont

**Comment by shayymaaxx** [comment]
they wont give up i mean

**Comment by oleanderghum** [comment]
I think I convinced them

**Comment by shayymaaxx** [comment]
we will see,  im not going to think about it now.
so you want me to pretend that we will never being together? or pretend what? we will never talk? 
what kind of “never contact”they want? never talk? never meet? or kind of normal teacher-student relationship?

**Comment by shayymaaxx** [comment]
They know that I will inevitably have contact with you in school as long as i stay at school, so expelling me is the best way. How can they give up? I wouldn't give it up if I were her. promise doesn't work, normal teacher and student doesn't work, only separated, completely ,works

**Comment by shayymaaxx** [comment]
so kind of her didn't tell it to your parents,, my heart kinda warmed to her kindness

**Comment by oleanderghum** [comment]
Yes, pretend all you mentioned. What would you do if they insist?

**Comment by shayymaaxx** [comment]
i don't know. 
it's impossible that we never meet and talk,doesn't she know? she knows. 
even though we keep a normal relationship we will still inevitably meet and talk,doesn't she know? she knows. she knows all these ,why she made herself convinced by you?

**Comment by oleanderghum** [comment]
I will stop them, whatever it takes

**Comment by shayymaaxx** [comment]
and, she's not in our college,how she knows that you talk to me or not? would she stop here and just believe in such an uncertainty? maybe she is thinking about to keep you and  separate me , she wants both

**Comment by shayymaaxx** [comment]
i wanna you promise me,don't make yourself so tired anymore, i truly don't know what to do if that happens, but if we still can't stop that,just let it. i deserve that,when i realized im into you i knew that, nothing regret.     
just.....sorry i can't do anything to get you to the peace, this exactly hurts me.

**Comment by oleanderghum** [comment]
Only when this pass I can breathe. I did't tell you the whole thing before because I knew you would be worry and afraid. Now you know, must be anxious bout it, I'm the one supposed to apologize.  I started it, I finish it, one thing I can promise is you won't get hurt from this.

**Comment by oleanderghum** [comment]
Whatever it takes.

**Comment by shayymaaxx** [comment]
and we're

**Comment by shayymaaxx** [comment]
done?

**Comment by oleanderghum** [comment]
Done what?

**Comment by shayymaaxx** [comment]
which means,

**Comment by shayymaaxx** [comment]
we are over?

**Comment by oleanderghum** [comment]
What? Why?

**Comment by oleanderghum** [comment]
I mean it's me put you in this jeopardy, and it should be me to get you out of it.

**Comment by oleanderghum** [comment]
What are you thinking?!

**Comment by shayymaaxx** [comment]
i don't know...i messed up your life, even can't fix it

**Comment by oleanderghum** [comment]
Are you with me?

**Comment by oleanderghum** [comment]
Stand by me?

**Comment by shayymaaxx** [comment]
yes and forever. 
but im always being the one only talk,the one mess everything up. you can't know how i feeling, that don't believe in myself anymore,I...even can't describe that.
feeling like I am buried under a huge rock, i can't move but damn i can still breathe

**Comment by shayymaaxx** [comment]
I can't imagine what you'll do to protect me, but I can feel your determination which will get you terrible injured in the war I know, this can only make me really afraid.
the worst thing will be im expelled, till then I will lose everything i have,could it be worse? no, then all bad things I took just helped me to strengthen the faith in me and you,I can have chances to restart everything.it couldn't be worse.
comparing this two things, I'd rather do my job to help you back to peace step by step. you are threatened and trapped because of me, if I truly quit,then everything settled. 
I love you and  after my former ambitions of occupying you , I found I can still love you by my own, you will pay too much if you want divorce,  im done asking for this.

**Comment by shayymaaxx** [comment]
maybe..... try to be nice to your wife, we're too expensive to be together, try to get back into your life, and it's only going to make your life easier, and I'll feel better.

**Comment by shayymaaxx** [comment]
im sorry .... i don't know what im talking about

**Comment by shayymaaxx** [comment]
just....tell me how I can help to get you out of such fucking terrible situation,tell me

**Comment by oleanderghum** [comment]
I will write a conversation sample, when we talk on the phone, speak as what sample shows.

**Comment by shayymaaxx** [comment]
you mean during this vocation or when we back to school?

**Comment by shayymaaxx** [comment]
and im not supposed to appear in your office anymore,right?

**Comment by oleanderghum** [comment]
I will call you tomorrow

**Comment by oleanderghum** [comment]
Yes

**Comment by oleanderghum** [comment]
On speaker

**Comment by shayymaaxx** [comment]
do I have to pick up the phone? what if I don't wanna hear your voice anymore?

**Comment by oleanderghum** [comment]
Why would you want that

**Comment by oleanderghum** [comment]
I thought we have reach consensus

**Comment by shayymaaxx** [comment]
don't need to write a so called sample, im good at being a cold girl and cutting off relationships.
unless you want any settled words that you have to want her to hear,just tell me

**Comment by shayymaaxx** [comment]
sure we reached

**Comment by oleanderghum** [comment]
It's in you mailbox

**Comment by shayymaaxx** [comment]
saw it

**Comment by shayymaaxx** [comment]
you are right,it's cruel indeed

**Comment by oleanderghum** [comment]
It is

**Comment by oleanderghum** [comment]
It is

**Comment by oleanderghum** [comment]
Hey you ok?

**Comment by shayymaaxx** [comment]
I'm fine

**Comment by oleanderghum** [comment]
Take
it 
easy

**Comment by oleanderghum** [comment]
I believe you're not happy on this, you don't even talk to me at all. Are you disappoint of me? Am I let you down?

**Comment by oleanderghum** [comment]
I will call you in the morning. Pick up after the third time I call. My lines may have some adjust but your answer doesn't need to.

**Comment by oleanderghum** [comment]
I know you saw the messages, you just don't want to reply me right?

**Comment by oleanderghum** [comment]
If you read this please reply

**Comment by shayymaaxx** [comment]
Just call

**Comment by oleanderghum** [comment]
This has to be done, I'm so sorry. All the words not what I meant to say, and you know it. Please forget what you hear and saw yesterday. Please remember what I told you in the bar of blackjack night, I love you.

**Comment by shayymaaxx** [comment]
I know you did it for me

**Comment by shayymaaxx** [comment]
I will not accuse you selfishly.

**Comment by oleanderghum** [comment]
I'm sorry, I guess it works

**Comment by oleanderghum** [comment]
Hey

**Comment by oleanderghum** [comment]
I miss you

**Comment by oleanderghum** [comment]
Many words, just missing

**Comment by oleanderghum** [comment]
No, you don't want to talk to me

**Comment by oleanderghum** [comment]
No way

**Comment by oleanderghum** [comment]
You're not gonna do that, right?

**Comment by shayymaaxx** [comment]
How's your situation? getting better?

**Comment by oleanderghum** [comment]
Thank god, I thought you don't want to talk to me anymore

**Comment by oleanderghum** [comment]
Still under surveillance

**Comment by shayymaaxx** [comment]
Guess it will follow you all the next three years

**Comment by shayymaaxx** [comment]
Sure i don't

**Comment by oleanderghum** [comment]
Three years? That would be fun

**Comment by oleanderghum** [comment]
Then I'd become a pycho killer

**Comment by shayymaaxx** [comment]
As long as I'm around,it will

**Comment by oleanderghum** [comment]
How are you doing these days

**Comment by shayymaaxx** [comment]
Fine, i guess

**Comment by oleanderghum** [comment]
Just fine? I want details

**Comment by shayymaaxx** [comment]
Nothing special,

**Comment by oleanderghum** [comment]
Remind me of a lyric

**Comment by oleanderghum** [comment]
As long as we are together,this fight will last forever, I'm running and running and running,and it's all for you,it's all for you

**Comment by shayymaaxx** [comment]
You can quiet it down

**Comment by oleanderghum** [comment]
Again??????

**Comment by shayymaa** [comment]
I deleted it.

**Comment by oleanderghum** [comment]
quiet it down>?

**Comment by oleanderghum** [comment]
means?

**Comment by shayymaa** [comment]
means

**Comment by shayymaa** [comment]
I don't know

**Comment by oleanderghum** [comment]
我心里很愧疚，非常愧疚。希望这几天你可以开开心心的，开开心心的过年。昨天梦到你，还写了首诗，只记得三句：众人说美，其美可说。人宴熙熙，人言戚戚。中年奔原，年老归田。也不知道什么意思。每天都在想着你，想很多。做什么事，听什么歌，都会想到你。想和你说话，想和你坐在一起，想你在身边。

**Comment by oleanderghum** [comment]
是对你的愧疚。

**Comment by oleanderghum** [comment]
总是回想你最美的样子。也许你会问我是什么时候的样子，我先不告诉你，我自己留着。

**Comment by shayymaa** [comment]
how about we end all it up in this sweet day ?

**Comment by oleanderghum** [comment]
Day is not, but the memories are sweet. Only you kill me can end this. Better find a bloody way for me. Cut me in pieces.

**Comment by shayymaa** [comment]
Yes you are right,memories are sweet ,they are always coming out on their own these days.

**Comment by shayymaa** [comment]
funny，huh？
I leave，I kill you. 
I don’t leave, you  kill me.

**Comment by shayymaa** [comment]
No it’s not you,actually it will be myself.I just can’t tolerate that the coming days I live around you but don’t meet don’t listen don’t talk don’t do anything but keep away from you  as much as I can ，this kill me .I know it  tortures you,too.

**Comment by shayymaa** [comment]
Don't you see that we have no hope at all?  I can see no hope of bettering this situation.

**Comment by shayymaa** [comment]
maybe only by ending all this can I break my thoughts of you，my desire for you，can help me to get over the next years.

**Comment by shayymaa** [comment]
Let me cut all these off ,bring you a easier life

**Comment by shayymaa** [comment]
Now ,of all things,I do not blame you, you also accompany me to where you can. you did a lot for me.

**Comment by shayymaa** [comment]
I made my peace with it, you make yours

**Comment by oleanderghum** [comment]
What do you need hope for? Hope is just a illusion, a lie. Why can't we meet? We can meet, we can talk, we can do a lot. It depends on you want it or not. You are not make my life easier. I don't give a shit about it's easy or hard. What I care about is life with you or without you. You asked me why did I do this, I'm telling you now. When you told me you broke up with you ex, I made up my mind to do something like this, some kind of balance. You pay, I pay.
But now, you are about to abandon the ship, and survive.
Whatever, I love you.

**Comment by shayymaa** [comment]
dreamed about you，we were back to the bar that day, You were sitting across from me, and the yellow light of the lamp is shining on your face. You didn’t say any word but staring at me,it was odd,cuz you look drunk and I don’t.   just like I'm a big drinker in my dream. then you left，somebody told me to wait for you，ｉwoke up

**Comment by oleanderghum** [comment]
Stay

**Comment by shayymaa** [comment]
here ｉam

**Comment by oleanderghum** [comment]
Don't hide, don't leave

**Comment by oleanderghum** [comment]
Don't be afraid

**Comment by shayymaa** [comment]
“喜欢”和“决定不要再喜欢了”之间是千丝万缕 反反复复的 怎么可能像关水龙头一样简单 一拧死 就一滴水都不出了。哪怕是在我恨极了你的时候，我的心脏也还是悄悄私自为你留了一段继续爱你的后路 它隐秘地绵延着 宽阔着 随时会被召回。
感情实在太不可控了 不可控到理智都忍不住为它退了一步又一步。即使是悬崖，理智让你勒马 爱他的心却让你终究纵身一跃了。
坠落时候刮到脸上的疾风 你都觉得甜。

**Comment by oleanderghum** [comment]
真想和你坐着聊聊天

**Comment by shayymaa** [comment]
我不贪心 像梦里那样看你我都开心

**Comment by oleanderghum** [comment]
今天很忙吧？

**Comment by shayymaa** [comment]
还好，就是帮厨 陪着打麻将，剩下都是吃吃喝喝

**Comment by shayymaa** [comment]
打麻将还赢了几百块哈哈哈  果真不会打的人手气旺

**Comment by oleanderghum** [comment]
通宵吗今天

**Comment by shayymaa** [comment]
不通 估计扛不住

**Comment by oleanderghum** [comment]
晚上要通宵打游戏，好久没玩了

**Comment by oleanderghum** [comment]
还是汉语用着顺畅啊……

**Comment by shayymaa** [comment]
对自己精力还挺自信

**Comment by shayymaa** [comment]
感觉被你带着英文都聊习惯了，为什么突然换中文了

**Comment by oleanderghum** [comment]
明明是你很爱说英语啊

**Comment by oleanderghum** [comment]
睡了睡了
本命年快乐 狗子

**Comment by shayymaa** [comment]
不不，聊英语都是你带的

**Comment by shayymaa** [comment]
新年快乐

**Comment by oleanderghum** [comment]
红shǎi儿上身了吗

**Comment by shayymaa** [comment]
Red socks☺

**Comment by oleanderghum** [comment]
是不是得顺便把一切头像都换成狗头呢？我推荐哈士奇

**Comment by oleanderghum** [comment]
![timg](https://user-images.githubusercontent.com/36097985/36337683-e241af26-13d6-11e8-93f5-03fe728d9146.jpg)

**Comment by shayymaa** [comment]
我脸那么肥的？

**Comment by oleanderghum** [comment]
![timg-1](https://user-images.githubusercontent.com/36097985/36337689-102233a2-13d7-11e8-8493-01e49599ec4d.jpg)

**Comment by oleanderghum** [comment]
这个瘦吧？

**Comment by shayymaa** [comment]
这个好这个好

**Comment by shayymaa** [comment]
不妥，哈士奇蠢得惊人。我这么聪明

**Comment by oleanderghum** [comment]
![timg-2](https://user-images.githubusercontent.com/36097985/36337704-6f10ad12-13d7-11e8-9432-89aadb25d024.jpg)

**Comment by oleanderghum** [comment]
听说你还会潜水，那这个最适合你了

**Comment by shayymaa** [comment]
大过年的不想打你哦

**Comment by oleanderghum** [comment]
萌蠢没听说过吗这个词，哈士奇狗中英杰

**Comment by oleanderghum** [comment]
还有一句话叫“大智若哈士奇”

**Comment by oleanderghum** [comment]
对于你这样一位青春期的少女需要这样的祝福相伴

**Comment by shayymaa** [comment]
萌我是赞同的，青春期也定位得非常准确

**Comment by shayymaa** [comment]
大智若哈士奇是你的座右铭？

**Comment by oleanderghum** [comment]
大智若哈士奇这个境界，这个定位，有点高山仰止了

**Comment by oleanderghum** [comment]
只有本命年的你才驾驭得了

**Comment by shayymaa** [comment]
你是说若我修得这智慧，保质期一年？

**Comment by oleanderghum** [comment]
一年修得十年受用啊

**Comment by shayymaa** [comment]
然后芳华早逝？

**Comment by oleanderghum** [comment]
哈哈怎么会

**Comment by oleanderghum** [comment]
自古女英雄出青春期

**Comment by shayymaa** [comment]
青春期透支完了

**Comment by oleanderghum** [comment]
不是，这句话虽然是我编的，但其中深意皆有据可考。

**Comment by oleanderghum** [comment]
刘胡兰，赵一曼，武曌，贞德，玛丽居里，克洛伊莫瑞兹etc.

**Comment by oleanderghum** [comment]
年纪轻轻大有作为，AMAZING TWENTY-THREE

**Comment by shayymaa** [comment]
这不是您二十三岁时的憧憬么

**Comment by oleanderghum** [comment]
我没有实现的，便把希望寄托在了你身上。

**Comment by oleanderghum** [comment]
😁

**Comment by shayymaa** [comment]
老……老父亲？

**Comment by oleanderghum** [comment]
开始唱~~~~~窝~~的

**Comment by shayymaa** [comment]
呸占便宜不带脸红的

**Comment by oleanderghum** [comment]
就是要占，要占尽

**Comment by shayymaa** [comment]
艾玛一个不设防就又被撩了

**Comment by oleanderghum** [comment]
别忘了头像啊，keep萌，stay蠢

**Comment by shayymaa** [comment]
换了你又看不到，没啥意义所以

**Comment by oleanderghum** [comment]
我看得到，你现在还是那个兔子头

**Comment by oleanderghum** [comment]
朋友圈背景还用那个傻大姐

**Comment by oleanderghum** [comment]
五福都不服，就福你

**Comment by oleanderghum** [comment]
我这边天很黑，但是没有星星

**Comment by oleanderghum** [comment]
想你了

**Comment by shayymaa** [comment]
我眼里有

**Comment by shayymaa** [comment]
我说星星

**Comment by oleanderghum** [comment]
那要让我看到

**Comment by shayymaa** [comment]
那你下次注意观察

**Comment by shayymaa** [comment]
想起来一首歌

**Comment by shayymaa** [comment]
我会让你心甘情愿把一切都给我
只要你看着我的双眼

**Comment by shayymaa** [comment]
我会让你跌入深不见底的快乐 
无法忘记我的双眼

**Comment by oleanderghum** [comment]
我听听

**Comment by shayymaa** [comment]
粉象难喝

**Comment by oleanderghum** [comment]
我带你喝才好喝

**Comment by oleanderghum** [comment]
下午离你家特别近

**Comment by shayymaa** [comment]
不喝了不喝了 喝吐了 喝得胃疼 肠胃炎都犯了

**Comment by shayymaa** [comment]
我家？中卫？

**Comment by oleanderghum** [comment]
你家，中卫。喝那么多干嘛，又不能喝

**Comment by shayymaa** [comment]
还好 想喝

**Comment by oleanderghum** [comment]
xx

**Comment by oleanderghum** [comment]
haha

**Comment by oleanderghum** [comment]
what if.........

**Comment by oleanderghum** [comment]
Time to get back😀

**Comment by oleanderghum** [comment]
uh....winter off is over, gotta start working tomorrow

**Comment by oleanderghum** [comment]
Know you will not back here

**Comment by shayymaa** [comment]
How’s your days

**Comment by oleanderghum** [comment]
上班下班

**Comment by shayymaa** [comment]
How's your office without me

**Comment by oleanderghum** [comment]
You wonder or you care

**Comment by shayymaa** [comment]
说不说！
